server:
  port: 8085


spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pugal0406/config-server
          clone-on-start: true